name: CI

on:
  pull_request:
    branches: [main, master]

# Add permissions to allow commenting on PRs
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        id: lint
        run: npm run lint
        continue-on-error: true

      - name: Run tests with coverage
        id: test
        run: npm run test:coverage
        continue-on-error: true

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const lintStatus = "${{ steps.lint.outcome }}" === "success" ? "✅ **Linting passed**" : "❌ **Linting failed**";
            const testStatus = "${{ steps.test.outcome }}" === "success" ? "✅ **Tests passed**" : "❌ **Tests failed**";

            const prComment = [
              "## ShapeShifter-MCP CI Results",
              "",
              lintStatus,
              testStatus,
              "",
              "### Details",
              `- **Repository:** ${context.repo.owner}/${context.repo.repo}`,
              `- **Pull Request:** #${context.issue.number}`,
              `- **Commit:** ${context.sha.substring(0, 7)}`,
              `- **Workflow Run:** [View full details](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`,
              "",
              "Thank you for your contribution! 🚀"
            ].join("\n");

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: prComment
            });

            // If any step failed, fail the workflow
            if ("${{ steps.lint.outcome }}" !== "success" || "${{ steps.test.outcome }}" !== "success") {
              core.setFailed("Lint or tests failed");
            }
